### PR TITLE
Support RAW content push [CLOUDDST-18677]

### PR DESCRIPTION
**Pull request by emilyzheng**
RAW files are pushed to CDN directly and not go into pulp repository. Get checksums from staging directory and downloadURL from checksum.

### CODE REVIEW

**Comment by emilyzheng** [comment]
@querti, @zxiong: I have no access to add reviewers. Please review :)

**Review by querti — APPROVED** [review]

**Comment by midnightercz** [comment]
Push item path is path to existing push item. Therefore you don't need to know destination path in advance, it's replaced by actual path when referred push item is pushed to the destination. Your PR changes this

**Comment by emilyzheng** [comment]
> Push item path is path to existing push item. Therefore you don't need to know destination path in advance, it's replaced by actual path when referred push item is pushed to the destination. Your PR changes this

For RAW content, a DirectoryPushItem is returned from pushsource. There's no push item of individual files, thus no push item path either.

**Comment by midnightercz** [comment]
> For RAW content, a DirectoryPushItem is returned from pushsource. There's no push item of individual files, thus no push item path either.

I understand why you did that but with this change you completely eliminate the possibility for the future. And I also find it strange that whole cgw was made for pulp as preparation step and suddenly there's no need to push to pulp. I would rather keep the possibility to do that in the future

**Comment by emilyzheng** [comment]
> And I also find it strange that whole cgw was made for pulp as preparation step and suddenly there's no need to push to pulp.

I reviewed the design doc 'Content Gateway Pub support'. RAW push was stated in the doc and FilePushItem was suggested in a comment, they are contradictory because RAW push doesn't create FilePushItem at all. I think there was a wrong assumption that files pushed for CGW purpose would have FilePushItems for sure. People involved in the discussion should know it better.

> I would rather keep the possibility to do that in the future

Possibility of supporting non-RAW content? Do we usually implement possibly useful features? When user wants A and not B, why not provide A first and add B later if it's requested? And B may never be requested.

**Review by midnightercz — APPROVED** [review]

**Pull request merged**
